import { Produto } from './produto';

const catalogo: Produto[] = [
  {
    id: 1,
    nome: 'GTA Sonic',
    titulo: 'Grand Theft Auto: Sonic Edition',
    genero: 'Ação / Sandbox / Comédia',
    plataforma: 'PlayStation 2 (Mod)',
    desenvolvedor: 'Modding Community / SEGA x Rockstar Fan Creation',
    imagem: 'Img1.png',
    descricao: 'Velocidade absurda pelas ruas de San Andreas.',
    preco: 20.00,
    descricaoDetalhada: 'O ouriço azul mais rápido do mundo resolveu trocar Green Hill Zone pelas ruas perigosas de San Andreas! Em GTA Sonic, a física de velocidade do universo SEGA se funde com o mundo aberto sem limites da Rockstar. Esqueça os carros: corra a centenas de quilômetros por hora a pé, salte por cima de prédios e crie o caos no trânsito com golpes giratórios.',
    destaques: ['Personagens Jogáveis: Sonic, Shadow, Knuckles, Amy Rose e Tails.', 'Super Velocidade: corra em velocidades absurdas pelas rodovias de Los Santos.', 'Super Pulos e Física Alterada: salte alturas inacreditáveis e explore o mapa.', 'Atmosfera Divertida: enfrente a polícia e descubra segredos espalhados pelo mapa.']
  },
  {
    id: 2,
    nome: 'GTA Dragon Ball',
    titulo: 'Grand Theft Auto: Dragon Ball Z Edition',
    genero: 'Ação / Luta / Sandbox',
    plataforma: 'PlayStation 2 (Mod - Geomatrix)',
    desenvolvedor: 'Geomatrix / Modding Community',
    imagem: 'img2.png',
    descricao: 'Guerreiros Saiyajins em um mundo aberto.',
    preco: 20.00,
    descricaoDetalhada: 'Eleve o seu Ki ao máximo no meio da cidade! GTA Dragon Ball traz o universo dos guerreiros Saiyajins para o mapa clássico de San Andreas. Transforme o dia a dia urbano em batalhas de proporções épicas, voando entre os arranha-céus e disparando rajadas de energia contra tanques e helicópteros do exército.',
    destaques: ['Elenco de Guerreiros Z: controle Vegeta, Goku, Trunks, Majin Boo e transformações.', 'Sistema de Voo Livre: decole a qualquer momento e explore San Andreas do alto.', 'Ataques Especiais: dispare Kamehamehas, Final Flashes e esferas de energia.', 'Interface Temática: sons, radar e HUD personalizados com o tema do anime.'],
    termosBusca: ['Dragon Ball Z']
  },
  {
    id: 3,
    nome: 'Dragon Ball Z: Budokai Tenkaichi 4',
    titulo: 'Dragon Ball Z: Budokai Tenkaichi 4 (Fan-Made Edition)',
    genero: 'Luta / 3D Arena Fighter',
    plataforma: 'PlayStation 2 (Patch Mod)',
    desenvolvedor: 'Team BT4 / SebLakes & Exorcist',
    imagem: 'img3.webp',
    descricao: 'A atualização dos sonhos para o lendário BT3.',
    preco: 25.00,
    descricaoDetalhada: 'O lendário Budokai Tenkaichi 3 recebeu a atualização dos sonhos! Desenvolvido com carinho por uma comunidade dedicada de fãs, BT4 expande o jogo original de PS2 trazendo toda a saga de Dragon Ball Super, transformações inéditas, novos cenários e ajustes de balanceamento no combate.',
    destaques: ['Roster Atualizado: Jiren, Goku Black, Hit, Whis, Bills e novas formas.', 'Trilha Sonora Épica: músicas das sagas clássicas e de Dragon Ball Super.', 'Novas Arenas e Golpes: Torneio do Poder e ataques especiais renovados.', 'Dublagem e Menus Atualizados: interface reformulada e opções de áudio.'],
    termosBusca: ['BT4', 'Budokai', 'Tenkaichi']
  },
  {
    id: 4,
    nome: 'Super Bomba Patch 2026',
    titulo: 'Super Bomba Patch 2026 - Edição Especial Mundial',
    genero: 'Esporte / Futebol',
    plataforma: 'PlayStation 2 (Patch)',
    desenvolvedor: 'Equipe Bomba Patch',
    imagem: 'img4.png',
    descricao: 'A temporada mundial mais atualizada do futebol.',
    preco: 25.00,
    descricaoDetalhada: '100% Atualizado, é ruim de aturar! O clássico imortal do futebol no PlayStation 2 está de volta na sua versão mais recente para a temporada de 2026! O Super Bomba Patch 2026 traz transferências, uniformes oficiais, seleções preparadas para a Copa e a clássica narração brasileira.',
    destaques: ['Elencos e Uniformes 2026: transferências recentes do futebol brasileiro e internacional.', 'Modo Seleções & Mundial: dispute o maior torneio do planeta.', 'Narração em Português: locução cheia de bordões marcantes.', 'Trilha Sonora Única: músicas e hinos do futebol nos menus.'],
    termosBusca: ['futebol', 'Bomba Patch']
  },
  {
    id: 5,
    nome: 'GTA São Paulo',
    titulo: 'Grand Theft Auto: São Paulo',
    genero: 'Ação / Sandbox Urbano',
    plataforma: 'PlayStation 2 (Mod)',
    desenvolvedor: 'Modding Community Brasil',
    imagem: 'img5.png',
    descricao: 'A selva de pedra com a cara do Brasil.',
    preco: 20.00,
    descricaoDetalhada: 'Bem-vindo à selva de pedra! GTA São Paulo adapta o clássico motor de San Andreas para homenagear a maior metrópole da América Latina. Pilotando carros e motos populares, você percorrerá vias inspiradas na rotina paulistana ao som de estações de rádio repletas de sucessos locais.',
    destaques: ['Frota Brasileira: carros, motos, viaturas e ônibus com visual brasileiro.', 'Estilo Urbano Paulista: roupas de marcas do streetwear nacional.', 'Rádios Locais: rap nacional, pagode, sertanejo e funk.', 'Ambientação Nostálgica: graffitis, outdoors e comércios em português.']
  },
  {
    id: 6,
    nome: 'GTA Rio de Janeiro',
    titulo: 'Grand Theft Auto: Rio de Janeiro - GOTY Edition',
    genero: 'Ação / Sandbox',
    plataforma: 'PlayStation 2 (Mod)',
    desenvolvedor: 'Brazilian Modding Legends',
    imagem: 'img6.png',
    descricao: 'A Cidade Maravilhosa no motor de San Andreas.',
    preco: 20.00,
    descricaoDetalhada: 'A modificação mais emblemática da história do PS2 no Brasil! GTA Rio de Janeiro transforma San Andreas na Cidade Maravilhosa. Visite o Cristo Redentor, passeie pelas praias com carros clássicos e sinta a atmosfera carioca dos anos 2000.',
    destaques: ['Pontos Turísticos: Cristo Redentor e paisagens inspiradas no Rio.', 'Trilha Sonora Imersiva: funk carioca antigo, pagode e samba.', 'Veículos Nacionais Clássicos: Gol, Palio, Uno, Marea e avião da Varig.', 'Roupas e Estilo: bermudas, camisas de times brasileiros e chinelos.']
  },
  {
    id: 7,
    nome: 'GTA Tropa de Elite',
    titulo: 'GTA San Andreas: Tropa de Elite - The Game',
    genero: 'Ação / Tiro / Tático',
    plataforma: 'PlayStation 2 (Mod)',
    desenvolvedor: 'Modding Community',
    imagem: 'img7.png',
    descricao: 'Operações táticas e ação nas áreas de risco.',
    preco: 20.00,
    descricaoDetalhada: 'Inspirado em um dos maiores fenômenos do cinema brasileiro, GTA Tropa de Elite coloca você no centro das operações táticas. Assuma o uniforme do BOPE ou enfrente os desafios das áreas de risco de San Andreas com viaturas operacionais e armamento pesado.',
    destaques: ['Skins e Fardamento Tático: vista a clássica farda preta do BOPE.', 'Viaturas Operacionais: veículos caracterizados com sirenes e pinturas temáticas.', 'Sons e Falas Marcantes: efeitos sonoros e falas inspiradas no filme.', 'Arsenal Modificado: armas de alto calibre para confrontos intensos.']
  },
  {
    id: 8,
    nome: 'Super Mario Collection',
    titulo: 'Super Mario Collection',
    genero: 'Plataforma / Coletânea',
    plataforma: 'PlayStation 2 (Bootleg / Emulator Disc)',
    desenvolvedor: 'Retro Homebrew Community',
    imagem: 'img8.png',
    descricao: 'Os maiores clássicos do encanador em um disco.',
    preco: 22.00,
    descricaoDetalhada: 'Toda a nostalgia dos jogos do encanador mais famoso do mundo reunida em um único disco para o seu PlayStation 2! Super Mario Collection é uma compilação especial com clássicos das eras 8-bits e 16-bits para jogar na TV da sala.',
    destaques: ['Vários Jogos em 1: Super Mario World, Super Mario Bros. 1, 2 e 3, Mario Kart retrô e mais.', 'Menu de Seleção Intuitivo: escolha facilmente qual jogo iniciar.', 'Jogabilidade Clássica: resposta rápida nos controles do PS2.', 'Ideal para Toda a Família: partidas leves e divertidas.']
  },
  {
    id: 9,
    nome: 'GTA Spider City',
    titulo: 'Grand Theft Auto: Spider City',
    genero: 'Ação / Super-Herói / Sandbox',
    plataforma: 'PlayStation 2 (Mod - Geomatrix)',
    desenvolvedor: 'Geomatrix / Modding Community',
    imagem: 'img9.png',
    descricao: 'Balance entre prédios e domine as ruas.',
    preco: 20.00,
    descricaoDetalhada: 'O que acontece quando o Homem-Aranha ganha liberdade total em uma grande metrópole sem regras? GTA Spider City substitui o protagonista pelo herói amigo da vizinhança. Balance entre prédios, suba em arranha-céus e use suas teias para dominar as ruas.',
    destaques: ['Mecânica de Teia e Escalada: movimente-se entre construções e escale paredes.', 'Trajes Variados: uniforme clássico e traje preto do Simbionte.', 'Acrobacias e Golpes: combate e saltos personalizados.', 'Mundo Aberto Liberado: explore a cidade e enfrente gangues locais.']
  },
  {
    id: 10,
    nome: 'Grand Theft Auto VI',
    titulo: 'Grand Theft Auto VI - Edition PS2',
    genero: 'Ação / Sandbox',
    plataforma: 'PlayStation 2 (Mod / Fan Tribute)',
    desenvolvedor: 'Underground Modders',
    imagem: 'img10.png',
    descricao: 'Uma homenagem neon e tropical para o PS2.',
    preco: 20.00,
    descricaoDetalhada: 'Uma homenagem divertida e lendária à cultura dos lançamentos antecipados das feiras de games! GTA VI para PS2 traz a atmosfera neon e tropical de Vice City para o motor gráfico clássico do PlayStation 2, com Jason, Lucia e um mapa cheio de carros esportivos e luzes reluzentes.',
    destaques: ['Atmosfera Vice City Neon: praias ensolaradas e noites neon.', 'Protagonistas Inéditos: skins de Lucia e Jason preparadas para a ação.', 'Supercarros Exóticos: carros de luxo e esportivos modernos.', 'Trilha Sonora Retrô-Futurista: synthwave, pop e hits das rádios locais.'],
    termosBusca: ['GTA VI', 'GTA 6', 'Vice City']
  },
  {
    id: 11,
    nome: 'WWE 2K17',
    titulo: 'WWE 2K17 (PlayStation 2 Edition)',
    genero: 'Luta / Esporte / Luta Livre (Wrestling)',
    plataforma: 'PlayStation 2 (Mod / Fan Edition)',
    desenvolvedor: '2K Sports / Modding Community',
    imagem: 'img11.jpg',
    descricao: 'Combates intensos e cinturões mundiais no ringue da WWE.',
    preco: 22.00,
    descricaoDetalhada: 'A Besta Encarnada Brock Lesnar domina o ringue na edição adaptada de WWE 2K17 para PlayStation 2! O jogo traz a atmosfera das grandes arenas da WWE, com elenco e identidade visual das edições modernas adaptados ao clássico motor de combate do PS2. Encare combates intensos, dispute cinturões mundiais e aplique golpes devastadores contra grandes nomes do wrestling.',
    destaques: ['Roster Atualizado: lutadores clássicos e astros das eras modernas.', 'Arenas Temáticas: WrestleMania, Royal Rumble e SummerSlam.', 'Variedade de Modos: Steel Cage, TLC, Royal Rumble e Tag Team.', 'Entradas e Temas: músicas e animações marcantes para cada lutador.'],
    termosBusca: ['Wrestling', 'WWE']
  },
  {
    id: 12,
    nome: 'GTA V Legacy',
    titulo: 'Grand Theft Auto V: Legacy Edition',
    genero: 'Ação / Sandbox / Mundo Aberto',
    plataforma: 'PlayStation 2 (Mod)',
    desenvolvedor: 'Rockstar Games / Underground Modding Team',
    imagem: 'img12.jpg',
    descricao: 'Los Santos e a atmosfera de GTA V adaptadas para o PS2.',
    preco: 20.00,
    descricaoDetalhada: 'Sinta o clima do lendário GTA V no console mais popular de todos os tempos! GTA V Legacy adapta o universo de Los Santos ao consagrado motor gráfico de San Andreas no PS2. Alterne entre visuais inspirados em Michael, Franklin e Trevor, pilote carros esportivos modernos e explore as ruas com elementos visuais do jogo original.',
    destaques: ['Protagonistas de GTA V: visuais inspirados em Michael, Franklin e Trevor.', 'Frota Moderna: carros esportivos, veículos de luxo e motos.', 'HUD Atualizado: radar, ícones de armas e menus personalizados.', 'Rádios Temáticas: músicas inspiradas nas estações marcantes da franquia.'],
    termosBusca: ['GTA V', 'GTA 5', 'Los Santos']
  },
  {
    id: 13,
    nome: 'Guitar Hero: Linkin Park',
    titulo: 'Guitar Hero: Linkin Park Edition',
    genero: 'Música / Ritmo',
    plataforma: 'PlayStation 2 (Mod)',
    desenvolvedor: 'Harmonix / RedOctane / Fan Community',
    imagem: 'img13.jpg',
    descricao: 'Toque os maiores sucessos do Linkin Park em uma edição especial.',
    preco: 22.00,
    descricaoDetalhada: 'Um tributo eletrizante a uma das maiores bandas de nu-metal e rock alternativo de todos os tempos! Guitar Hero: Linkin Park reúne sucessos da banda em um disco exclusivo para PS2. Solte a voz com as linhas marcantes de Chester Bennington e toque riffs em faixas inesquecíveis.',
    destaques: ['Tracklist de Sucessos: faixas de Hybrid Theory, Meteora e outros álbuns.', 'Palcos Temáticos: ambientes com a identidade visual da banda.', 'Dificuldade Progressiva: partituras do Easy ao Expert.', 'Compatibilidade: jogue com guitarra de plástico ou controle padrão do PS2.'],
    termosBusca: ['Guitar Hero', 'Linkin Park', 'música', 'ritmo']
  },
  {
    id: 14,
    nome: "Guitar Hero III: Guns N' Roses",
    titulo: "Guitar Hero III: Guns N' Roses Edition",
    genero: 'Música / Ritmo / Hard Rock',
    plataforma: 'PlayStation 2 (Mod)',
    desenvolvedor: 'Neversoft / Activision / Fan Edition',
    imagem: 'img14.jpg',
    descricao: "Solos de guitarra e clássicos do Guns N' Roses.",
    preco: 22.00,
    descricaoDetalhada: "Coloque o chapéu do Slash e prepare os dedos para os solos de guitarra mais épicos da história do rock! Guitar Hero III: Guns N' Roses é uma edição customizada dedicada à discografia da lendária banda norte-americana. Desafie seus reflexos em hinos que marcaram gerações.",
    destaques: ["Setlist Clássico: Sweet Child O' Mine, Welcome to the Jungle, Paradise City e November Rain.", "Estética Rock 'n' Roll: menus e artes com o estilo visual da banda.", 'Solos Desafiadores: notas mapeadas para testar sua agilidade.', 'Áudio Otimizado: faixas preparadas para uma experiência imersiva.'],
    termosBusca: ['Guitar Hero', 'Guns N Roses', 'rock']
  },
  {
    id: 15,
    nome: 'Super Collection',
    titulo: 'Super Collection (Multi-Console Emulator Disc)',
    genero: 'Coletânea / Plataforma / Retrô',
    plataforma: 'PlayStation 2 (Bootleg / Emulator Disc)',
    desenvolvedor: 'Retro Homebrew Community',
    imagem: 'img15.jpg',
    descricao: 'Centenas de jogos clássicos de Atari, Nintendo e SEGA em um disco.',
    preco: 25.00,
    descricaoDetalhada: 'Uma enciclopédia dos games da era de ouro reunida em um único disco para o PS2! Super Collection traz uma compilação de emuladores e jogos clássicos das eras 8-bits e 16-bits, reunindo ícones como Mario, Sonic e Pac-Man em uma só interface.',
    destaques: ['Centenas de Jogos: clássicos de Atari, NES, Master System, Mega Drive e Super Nintendo.', 'Menu Intuitivo: escolha a plataforma e inicie o jogo desejado.', 'Save State: salve o progresso no Memory Card do PlayStation 2.', 'Multiplayer: jogue com outra pessoa usando o segundo controle.'],
    termosBusca: ['Atari', 'Nintendo', 'SEGA', 'retrô', 'emulador']
  },
  {
    id: 16,
    nome: 'Guitar Hero III: Iron Maiden',
    titulo: 'Guitar Hero III: Iron Maiden Edition',
    genero: 'Música / Ritmo / Heavy Metal',
    plataforma: 'PlayStation 2 (Mod)',
    desenvolvedor: 'Dark_Shadow / Fan Modding',
    imagem: 'img16.jpg',
    descricao: 'Encare solos velozes e clássicos da Donzela de Ferro.',
    preco: 22.00,
    descricaoDetalhada: 'Up the Irons! Guitar Hero III: Iron Maiden leva a energia das turnês da Donzela de Ferro para o PlayStation 2. Enfrente solos velozes e linhas marcantes de baixo enquanto acompanha Eddie através da trajetória de uma das maiores bandas de heavy metal do planeta.',
    destaques: ['Setlist Heavy Metal: clássicos como The Number of the Beast, Run to the Hills e Fear of the Dark.', 'Visual de Eddie: menus e artes inspirados nos álbuns e na banda.', 'Desafio em Alta Velocidade: notas complexas para jogadores experientes.', 'Trilhas Remasterizadas: guitarras duplas com áudio otimizado.'],
    termosBusca: ['Guitar Hero', 'Iron Maiden', 'metal']
  },
  {
    id: 17,
    nome: 'Guitar Hero Brazucas',
    titulo: 'Guitar Hero Brazucas',
    genero: 'Música / Ritmo / Rock Nacional',
    plataforma: 'PlayStation 2 (Mod)',
    desenvolvedor: 'Comunidade Modder Brasileira',
    imagem: 'img17.jpg',
    descricao: 'Rock e pop rock nacional para tocar e cantar junto.',
    preco: 22.00,
    descricaoDetalhada: 'Um dos maiores fenômenos da história dos consoles no Brasil! Guitar Hero Brazucas é uma modificação dedicada ao rock e pop rock nacional. Toque faixas que dominaram as rádios brasileiras nos anos 90 e 2000, de Mamonas Assassinas a Massacration.',
    destaques: ['Repertório Nacional: Mamonas Assassinas, Charlie Brown Jr., Pitty, CPM 22, Angra, Titãs e mais.', 'Menus em Português: interface adaptada para facilitar a navegação.', 'Nostalgia: músicas brasileiras que marcaram encontros entre amigos.', 'Controles Compatíveis: jogue com guitarras de PS2 ou controles padrão.'],
    termosBusca: ['Guitar Hero', 'Brazucas', 'rock nacional', 'Mamonas', 'Charlie Brown Jr.']
  }
].map((produto) => ({
  ...produto,
  precoPromocional: Number((produto.preco * 0.5).toFixed(2))
}));

export const produtos: Produto[] = catalogo;