import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Produto } from '../model/produto';
import { ActivatedRoute, RouterLink } from '@angular/router';

@Component({
  imports: [CommonModule, RouterLink],
  selector: 'app-detalhe',
  styleUrl: './detalhe.css',
  templateUrl: './detalhe.html',
})
export class Detalhe implements OnInit {
  produto?: Produto;

  constructor(private readonly route: ActivatedRoute) {}

  ngOnInit(): void {
    const id = Number(this.route.snapshot.paramMap.get('id'));
    this.produto = this.lista.find((item) => item.id === id);
  }

  lista: Produto[] = [
    { id: 1, nome: 'GTA Sonic', titulo: 'Grand Theft Auto: Sonic Edition', genero: 'Ação / Sandbox / Comédia', plataforma: 'PlayStation 2 (Mod)', desenvolvedor: 'Modding Community / SEGA x Rockstar Fan Creation', imagem: 'Img1.png', descricao: 'Velocidade absurda pelas ruas de San Andreas.', preco: 98.90, precoPromocional: 76.90, descricaoDetalhada: 'O ouriço azul mais rápido do mundo resolveu trocar Green Hill Zone pelas ruas perigosas de San Andreas! Em GTA Sonic, a física de velocidade do universo SEGA se funde com o mundo aberto sem limites da Rockstar. Esqueça os carros: corra a centenas de quilômetros por hora a pé, salte por cima de prédios e crie o caos no trânsito com golpes giratórios.', destaques: ['Personagens Jogáveis: Sonic, Shadow, Knuckles, Amy Rose e Tails.', 'Super Velocidade: corra em velocidades absurdas pelas rodovias de Los Santos.', 'Super Pulos e Física Alterada: salte alturas inacreditáveis e explore o mapa.', 'Atmosfera Divertida: enfrente a polícia e descubra segredos espalhados pelo mapa.'] },
    { id: 2, nome: 'GTA Dragon Ball', titulo: 'Grand Theft Auto: Dragon Ball Z Edition', genero: 'Ação / Luta / Sandbox', plataforma: 'PlayStation 2 (Mod - Geomatrix)', desenvolvedor: 'Geomatrix / Modding Community', imagem: 'img2.png', descricao: 'Guerreiros Saiyajins em um mundo aberto.', preco: 109.90, precoPromocional: 87.90, descricaoDetalhada: 'Eleve o seu Ki ao máximo no meio da cidade! GTA Dragon Ball traz o universo dos guerreiros Saiyajins para o mapa clássico de San Andreas. Transforme o dia a dia urbano em batalhas de proporções épicas, voando entre os arranha-céus e disparando rajadas de energia contra tanques e helicópteros do exército.', destaques: ['Elenco de Guerreiros Z: controle Vegeta, Goku, Trunks, Majin Boo e transformações.', 'Sistema de Voo Livre: decole a qualquer momento e explore San Andreas do alto.', 'Ataques Especiais: dispare Kamehamehas, Final Flashes e esferas de energia.', 'Interface Temática: sons, radar e HUD personalizados com o tema do anime.'] },
    { id: 3, nome: 'Dragon Ball Z: Budokai Tenkaichi 4', titulo: 'Dragon Ball Z: Budokai Tenkaichi 4 (Fan-Made Edition)', genero: 'Luta / 3D Arena Fighter', plataforma: 'PlayStation 2 (Patch Mod)', desenvolvedor: 'Team BT4 / SebLakes & Exorcist', imagem: 'img3.webp', descricao: 'A atualização dos sonhos para o lendário BT3.', preco: 119.90, precoPromocional: 94.90, descricaoDetalhada: 'O lendário Budokai Tenkaichi 3 recebeu a atualização dos sonhos! Desenvolvido com carinho por uma comunidade dedicada de fãs, BT4 expande o jogo original de PS2 trazendo toda a saga de Dragon Ball Super, transformações inéditas, novos cenários e ajustes de balanceamento no combate.', destaques: ['Roster Atualizado: Jiren, Goku Black, Hit, Whis, Bills e novas formas.', 'Trilha Sonora Épica: músicas das sagas clássicas e de Dragon Ball Super.', 'Novas Arenas e Golpes: Torneio do Poder e ataques especiais renovados.', 'Dublagem e Menus Atualizados: interface reformulada e opções de áudio.'] },
    { id: 4, nome: 'Super Bomba Patch 2026', titulo: 'Super Bomba Patch 2026 - Edição Especial Mundial', genero: 'Esporte / Futebol', plataforma: 'PlayStation 2 (Patch)', desenvolvedor: 'Equipe Bomba Patch', imagem: 'img4.png', descricao: 'A temporada mundial mais atualizada do futebol.', preco: 89.90, precoPromocional: 69.90, descricaoDetalhada: '100% Atualizado, é ruim de aturar! O clássico imortal do futebol no PlayStation 2 está de volta na sua versão mais recente para a temporada de 2026! O Super Bomba Patch 2026 traz transferências, uniformes oficiais, seleções preparadas para a Copa e a clássica narração brasileira.', destaques: ['Elencos e Uniformes 2026: transferências recentes do futebol brasileiro e internacional.', 'Modo Seleções & Mundial: dispute o maior torneio do planeta.', 'Narração em Português: locução cheia de bordões marcantes.', 'Trilha Sonora Única: músicas e hinos do futebol nos menus.'] },
    { id: 5, nome: 'GTA São Paulo', titulo: 'Grand Theft Auto: São Paulo', genero: 'Ação / Sandbox Urbano', plataforma: 'PlayStation 2 (Mod)', desenvolvedor: 'Modding Community Brasil', imagem: 'img5.png', descricao: 'A selva de pedra com a cara do Brasil.', preco: 98.90, precoPromocional: 76.90, descricaoDetalhada: 'Bem-vindo à selva de pedra! GTA São Paulo adapta o clássico motor de San Andreas para homenagear a maior metrópole da América Latina. Pilotando carros e motos populares, você percorrerá vias inspiradas na rotina paulistana ao som de estações de rádio repletas de sucessos locais.', destaques: ['Frota Brasileira: carros, motos, viaturas e ônibus com visual brasileiro.', 'Estilo Urbano Paulista: roupas de marcas do streetwear nacional.', 'Rádios Locais: rap nacional, pagode, sertanejo e funk.', 'Ambientação Nostálgica: graffitis, outdoors e comércios em português.'] },
    { id: 6, nome: 'GTA Rio de Janeiro', titulo: 'Grand Theft Auto: Rio de Janeiro - GOTY Edition', genero: 'Ação / Sandbox', plataforma: 'PlayStation 2 (Mod)', desenvolvedor: 'Brazilian Modding Legends', imagem: 'img6.png', descricao: 'A Cidade Maravilhosa no motor de San Andreas.', preco: 98.90, precoPromocional: 76.90, descricaoDetalhada: 'A modificação mais emblemática da história do PS2 no Brasil! GTA Rio de Janeiro transforma San Andreas na Cidade Maravilhosa. Visite o Cristo Redentor, passeie pelas praias com carros clássicos e sinta a atmosfera carioca dos anos 2000.', destaques: ['Pontos Turísticos: Cristo Redentor e paisagens inspiradas no Rio.', 'Trilha Sonora Imersiva: funk carioca antigo, pagode e samba.', 'Veículos Nacionais Clássicos: Gol, Palio, Uno, Marea e avião da Varig.', 'Roupas e Estilo: bermudas, camisas de times brasileiros e chinelos.'] },
    { id: 7, nome: 'GTA Tropa de Elite', titulo: 'GTA San Andreas: Tropa de Elite - The Game', genero: 'Ação / Tiro / Tático', plataforma: 'PlayStation 2 (Mod)', desenvolvedor: 'Modding Community', imagem: 'img7.png', descricao: 'Operações táticas e ação nas áreas de risco.', preco: 109.90, precoPromocional: 84.90, descricaoDetalhada: 'Inspirado em um dos maiores fenômenos do cinema brasileiro, GTA Tropa de Elite coloca você no centro das operações táticas. Assuma o uniforme do BOPE ou enfrente os desafios das áreas de risco de San Andreas com viaturas operacionais e armamento pesado.', destaques: ['Skins e Fardamento Tático: vista a clássica farda preta do BOPE.', 'Viaturas Operacionais: veículos caracterizados com sirenes e pinturas temáticas.', 'Sons e Falas Marcantes: efeitos sonoros e falas inspiradas no filme.', 'Arsenal Modificado: armas de alto calibre para confrontos intensos.'] },
    { id: 8, nome: 'Super Mario Collection', titulo: 'Super Mario Collection', genero: 'Plataforma / Coletânea', plataforma: 'PlayStation 2 (Bootleg / Emulator Disc)', desenvolvedor: 'Retro Homebrew Community', imagem: 'img8.png', descricao: 'Os maiores clássicos do encanador em um disco.', preco: 79.90, precoPromocional: 59.90, descricaoDetalhada: 'Toda a nostalgia dos jogos do encanador mais famoso do mundo reunida em um único disco para o seu PlayStation 2! Super Mario Collection é uma compilação especial com clássicos das eras 8-bits e 16-bits para jogar na TV da sala.', destaques: ['Vários Jogos em 1: Super Mario World, Super Mario Bros. 1, 2 e 3, Mario Kart retrô e mais.', 'Menu de Seleção Intuitivo: escolha facilmente qual jogo iniciar.', 'Jogabilidade Clássica: resposta rápida nos controles do PS2.', 'Ideal para Toda a Família: partidas leves e divertidas.'] },
    { id: 9, nome: 'GTA Spider City', titulo: 'Grand Theft Auto: Spider City', genero: 'Ação / Super-Herói / Sandbox', plataforma: 'PlayStation 2 (Mod - Geomatrix)', desenvolvedor: 'Geomatrix / Modding Community', imagem: 'img9.png', descricao: 'Balance entre prédios e domine as ruas.', preco: 109.90, precoPromocional: 84.90, descricaoDetalhada: 'O que acontece quando o Homem-Aranha ganha liberdade total em uma grande metrópole sem regras? GTA Spider City substitui o protagonista pelo herói amigo da vizinhança. Balance entre prédios, suba em arranha-céus e use suas teias para dominar as ruas.', destaques: ['Mecânica de Teia e Escalada: movimente-se entre construções e escale paredes.', 'Trajes Variados: uniforme clássico e traje preto do Simbionte.', 'Acrobacias e Golpes: combate e saltos personalizados.', 'Mundo Aberto Liberado: explore a cidade e enfrente gangues locais.'] },
    { id: 10, nome: 'Grand Theft Auto VI', titulo: 'Grand Theft Auto VI - Edition PS2', genero: 'Ação / Sandbox', plataforma: 'PlayStation 2 (Mod / Fan Tribute)', desenvolvedor: 'Underground Modders', imagem: 'img10.png', descricao: 'Uma homenagem neon e tropical para o PS2.', preco: 129.90, precoPromocional: 99.90, descricaoDetalhada: 'Uma homenagem divertida e lendária à cultura dos lançamentos antecipados das feiras de games! GTA VI para PS2 traz a atmosfera neon e tropical de Vice City para o motor gráfico clássico do PlayStation 2, com Jason, Lucia e um mapa cheio de carros esportivos e luzes reluzentes.', destaques: ['Atmosfera Vice City Neon: praias ensolaradas e noites neon.', 'Protagonistas Inéditos: skins de Lucia e Jason preparadas para a ação.', 'Supercarros Exóticos: carros de luxo e esportivos modernos.', 'Trilha Sonora Retrô-Futurista: synthwave, pop e hits das rádios locais.'] }
  ];
}
